/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'status' : AttendanceStatus,
  'studentId' : Principal,
  'date' : bigint,
}
export type AttendanceStatus = { 'present' : null } |
  { 'absent' : null };
export interface Complaint {
  'id' : bigint,
  'studentId' : Principal,
  'message' : string,
  'timestamp' : bigint,
}
export interface Event {
  'id' : bigint,
  'title' : string,
  'date' : bigint,
  'description' : string,
}
export interface Mark {
  'studentId' : Principal,
  'semester' : bigint,
  'maxScore' : bigint,
  'subject' : string,
  'score' : bigint,
}
export interface Semester {
  'id' : bigint,
  'endDate' : bigint,
  'name' : string,
  'startDate' : bigint,
}
export interface SemesterExamResult {
  'studentId' : Principal,
  'maxScore' : bigint,
  'subject' : string,
  'semesterId' : bigint,
  'score' : bigint,
}
export interface Student {
  'id' : Principal,
  'username' : string,
  'password' : string,
  'name' : string,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAttendance' : ActorMethod<
    [Principal, bigint, AttendanceStatus],
    undefined
  >,
  'addMark' : ActorMethod<
    [Principal, string, bigint, bigint, bigint],
    undefined
  >,
  'addSemester' : ActorMethod<[string, bigint, bigint], undefined>,
  'addSemesterExamResult' : ActorMethod<
    [Principal, bigint, string, bigint, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEvent' : ActorMethod<[string, string, bigint], undefined>,
  'createStudent' : ActorMethod<[string, string, string], undefined>,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'getAllComplaints' : ActorMethod<[], Array<Complaint>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllMarks' : ActorMethod<[], Array<Mark>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAttendanceAll' : ActorMethod<[], Array<Attendance>>,
  'getAttendanceByStudent' : ActorMethod<[Principal], Array<Attendance>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMarksByStudent' : ActorMethod<[Principal], Array<Mark>>,
  'getSemesterExamResultsByStudent' : ActorMethod<
    [Principal],
    Array<SemesterExamResult>
  >,
  'getSemesters' : ActorMethod<[], Array<Semester>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'studentLogin' : ActorMethod<[string, string], boolean>,
  'submitComplaint' : ActorMethod<[string], undefined>,
  'updateAttendance' : ActorMethod<
    [Principal, bigint, AttendanceStatus],
    undefined
  >,
  'updateEvent' : ActorMethod<[bigint, string, string, bigint], undefined>,
  'updateMark' : ActorMethod<
    [Principal, string, bigint, bigint, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];