/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'absent' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Complaint = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Int,
  'description' : IDL.Text,
});
export const Mark = IDL.Record({
  'studentId' : IDL.Principal,
  'semester' : IDL.Nat,
  'maxScore' : IDL.Nat,
  'subject' : IDL.Text,
  'score' : IDL.Nat,
});
export const Student = IDL.Record({
  'id' : IDL.Principal,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'name' : IDL.Text,
});
export const Attendance = IDL.Record({
  'status' : AttendanceStatus,
  'studentId' : IDL.Principal,
  'date' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const SemesterExamResult = IDL.Record({
  'studentId' : IDL.Principal,
  'maxScore' : IDL.Nat,
  'subject' : IDL.Text,
  'semesterId' : IDL.Nat,
  'score' : IDL.Nat,
});
export const Semester = IDL.Record({
  'id' : IDL.Nat,
  'endDate' : IDL.Int,
  'name' : IDL.Text,
  'startDate' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAttendance' : IDL.Func(
      [IDL.Principal, IDL.Int, AttendanceStatus],
      [],
      [],
    ),
  'addMark' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'addSemester' : IDL.Func([IDL.Text, IDL.Int, IDL.Int], [], []),
  'addSemesterExamResult' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
  'createStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllMarks' : IDL.Func([], [IDL.Vec(Mark)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAttendanceAll' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
  'getAttendanceByStudent' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMarksByStudent' : IDL.Func([IDL.Principal], [IDL.Vec(Mark)], ['query']),
  'getSemesterExamResultsByStudent' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(SemesterExamResult)],
      ['query'],
    ),
  'getSemesters' : IDL.Func([], [IDL.Vec(Semester)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'studentLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'submitComplaint' : IDL.Func([IDL.Text], [], []),
  'updateAttendance' : IDL.Func(
      [IDL.Principal, IDL.Int, AttendanceStatus],
      [],
      [],
    ),
  'updateEvent' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Int], [], []),
  'updateMark' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'absent' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Complaint = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Int,
    'description' : IDL.Text,
  });
  const Mark = IDL.Record({
    'studentId' : IDL.Principal,
    'semester' : IDL.Nat,
    'maxScore' : IDL.Nat,
    'subject' : IDL.Text,
    'score' : IDL.Nat,
  });
  const Student = IDL.Record({
    'id' : IDL.Principal,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'name' : IDL.Text,
  });
  const Attendance = IDL.Record({
    'status' : AttendanceStatus,
    'studentId' : IDL.Principal,
    'date' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const SemesterExamResult = IDL.Record({
    'studentId' : IDL.Principal,
    'maxScore' : IDL.Nat,
    'subject' : IDL.Text,
    'semesterId' : IDL.Nat,
    'score' : IDL.Nat,
  });
  const Semester = IDL.Record({
    'id' : IDL.Nat,
    'endDate' : IDL.Int,
    'name' : IDL.Text,
    'startDate' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAttendance' : IDL.Func(
        [IDL.Principal, IDL.Int, AttendanceStatus],
        [],
        [],
      ),
    'addMark' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'addSemester' : IDL.Func([IDL.Text, IDL.Int, IDL.Int], [], []),
    'addSemesterExamResult' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
    'createStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllMarks' : IDL.Func([], [IDL.Vec(Mark)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAttendanceAll' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
    'getAttendanceByStudent' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMarksByStudent' : IDL.Func([IDL.Principal], [IDL.Vec(Mark)], ['query']),
    'getSemesterExamResultsByStudent' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SemesterExamResult)],
        ['query'],
      ),
    'getSemesters' : IDL.Func([], [IDL.Vec(Semester)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'studentLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'submitComplaint' : IDL.Func([IDL.Text], [], []),
    'updateAttendance' : IDL.Func(
        [IDL.Principal, IDL.Int, AttendanceStatus],
        [],
        [],
      ),
    'updateEvent' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Int], [], []),
    'updateMark' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };